### ISSUE TITLE
TCP Unicast fails on CLI tool, while working on GUI version

### ISSUE THREAD

**Issue by fvarandas** [Wiznet/WIZnet-S2E-Tool#11]
Comparing `wizconfig.py` with their `main_gui.py` counterpart on [WIZnet-S2E-Tool-GUI repo](https://github.com/Wiznet/WIZnet-S2E-Tool-GUI/blob/master/main_gui.py), the following vars seem off:

WIZnet-S2E-Tool:
```
SOCK_CLOSE_STATE = 21
SOCK_OPENTRY_STATE = 22
SOCK_OPEN_STATE = 23
SOCK_CONNECTTRY_STATE = 24
SOCK_CONNECT_STATE = 25
```

WIZnet-S2E-Tool-GUI:
```
SOCK_CLOSE_STATE = 1
SOCK_OPENTRY_STATE = 2
SOCK_OPEN_STATE = 3
SOCK_CONNECTTRY_STATE = 4
SOCK_CONNECT_STATE = 5
```

If you use the values of WIZnet-S2E-Tool-GUI on the WIZnet-S2E-Tool, TCP unicast seems to work.

**Comment by renakim** [comment]
@fvarandas Thank you for leaving the issue.
I'll check the function and update.

**Comment by renakim** [comment]
@fvarandas The issue is fixed. 
Thanks again 👍
