### ISSUE TITLE
Not working on Linux (no errors either)

### ISSUE THREAD

**Issue by pakmans** [Wiznet/WIZnet-S2E-Tool#5]
Environment: Ubuntu Bionic (18.04), python 3.6.5

****UPDATE:**** I think my device (WIZ110SR) is not supported by this tool.

The device is working and can be found and configured from windows gui, but not with linux cli nor linux gui.

&#35; python3 wizconfig.py -s
Devcie configuration start...
Start to Search devices...
Search result: 0 devices are detected
Refer to 'mac_list.txt' file

The devcie is working fine. I can send commands (i.e. via telnet) and it works.
I can see it fine in the local network:

&#35; arp-scan --localnet
Interface: enx9cebe815f5f4, datalink type: EN10MB (Ethernet)
Starting arp-scan 1.9 with 256 hosts (http://www.nta-monitor.com/tools/arp-scan/)
192.168.1.102	00:08:dc:4f:3e:0c	Wiznet

**Comment by renakim** [comment]
>  I think my device (WIZ110SR) is not supported by this tool.

That's right.
WIZ110SR is not supported because the command list is different.

Thank you.

**Comment by pakmans** [comment]
Sorry for posting in a closed issue, but is there a Linux CLI or GUI to configure the WIZ110SR?
I can't seem to find one.

**Comment by fkrieg** [comment]
@pakmans This is what you are searching: https://github.com/zehome/wiznetconfigurator

**Comment by renakim** [comment]
@fkrieg Thank you.

@pakmans How about try use WIZ750SR-110?
WIZ750SR-110 is compatible with the WIZ110SR module and CLI & GUI Tool is supported.
Refer to this: [WIZwiki: WIZ750SR-110](https://wizwiki.net/wiki/doku.php?id=products:wiz750sr-110:start)

**Comment by pakmans** [comment]
@renakim  I was given some equipment that uses WIZ110SR... I can't change that. Thanks for the info though.
