### ISSUE TITLE
Bug correction

### ISSUE THREAD

**Issue by pccbezerra** [Wiznet/WIZnet-S2E-Tool#8]
I am a "lucky" guy who got a WIZ device with MAC 00:08:DC:56:52:92, so when using WIZnet-S2E-Tool, it bugs beliving that the 56:52 is VR, and breaks the search.
Solution is changing 
    if b'VR' in replylists[i]:
for 
   if b'VR' in replylists[i][:2] :                                
@function parseresponse of WIZMSGHandler.py

the same should be done to MC, MN ...

Regards

**Comment by renakim** [comment]
Hello @pccbezerra, thank you for the issue.
on [WIZnet-S2E-Tool-GUI](https://github.com/Wiznet/WIZnet-S2E-Tool-GUI), there was a similar issue so I updated function. (not use 'MA' parameter and check parameter)
I applied the same function to CLI Tool. Refer to #9 
Thanks.

**Comment by pccbezerra** [comment]
Tested, and working.
Thank you.
